Updating the invite flow to not use a slack invite url and rather go through manual-email-flow.
zatech/site pull request #3
Opened 2022-07-11 12:40 UTC by n1c

## Old:
![image](https://user-images.githubusercontent.com/284075/178266121-665ab88a-e72d-4be6-b397-5d7ed7e77889.png)

## New:
![image](https://user-images.githubusercontent.com/284075/178266040-a1ff2d90-170b-4cc9-a5b3-f5931b14b045.png)

2022-07-12 10:12 UTC, JohnRoux commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
Probably worth adding some default formatting and subject there to help standardize things:

```suggestion
                <strong>WANT AN INVITE?</strong> Send an <a target="_blank" href="mailto:invite@zatech.co.za?subject=New User Invite&body=Hi,%0D%0A%0D%0AI'd like an invite please!%0D%0A%0D%0AName: %0D%0AOccupation: %0D%0AWhy I want to join (1 liner): %0D%0AWhere you heard about us: %0D%0ALink to LinkedIn/Twitter/Medium/Facebook etc:">email</a> from an email account you're going to use for a long time (not your work email — you'll be in this community awhile). Include your name, occupation, a brief explanation of why you want to join the Slack, and how you heard about us. Finally, please include a link to your LinkedIn, Twitter, or Medium — any site that demonstrates you're a human. <strong>None</strong> of the above information will be shared with anyone but the admin team.
```

2022-07-12 10:15 UTC, JohnRoux requested changes
Solid, minor update to the invite link will likely provide large value for admins :+1:

2022-07-12 11:05 UTC, n1c commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
I prefer the idea of making the user do all the work, it forms quite a big part of the "human test" for me.

2022-07-12 11:07 UTC, JohnRoux commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
They're going to have to actually fill it in and send it. That _is_ all the work :D

Formatting it nicely is just going to make our lives a ton easier to parse the mess

People are 100% going to miss things and it's a ton easier having a set format imho

2022-07-20 07:29 UTC, ChristianWitts commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
I'd lean towards a checklist for folks to complete, as I don't know many/any folks who have a desktop email client these days.

2022-07-20 08:01 UTC, JohnRoux commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
Do we have GA trackijg on that page btw? Would be interestijg to know the mobile vs desktop split.

But yeah, that's fair. Though you can setup Gmail in web view to act as your default mail client. My mailto links open in a new browser tab of Gmail.


Both might be a decent option

2022-07-20 08:03 UTC, schalkventer commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
Yeah, I'd agree with @JohnRoux on this one - as a rule of thumb I tend to expect the worst from anyone using something I create.

2022-07-20 08:03 UTC, schalkventer commented on resources/views/welcome.blade.php
> +                <strong>WANT AN INVITE?</strong> Send an <a href="mailto:invite@zatech.co.za">email</a> from an email account you're going to use for a long time (not your work email — you'll be in t
Would make filtering/searching also easier if it is atleast placeholder text instead of just a blank subject.

2022-08-18 09:55 UTC, merged